Error in case of an unchanged config
tarantool/cartridge pull request #1317
Opened 2021-03-15 14:44 UTC by Steap2448

The ``patch_clusterwide`` function shouldn't skip a 2pc upload if nothing changed. Instead, it'll do fair ``upload`` and ``prepare_2pc``. And the ``commit_2pc`` on every instance can then decide if the instance state is suitable for the skipping. If there are no changes in prepared config it will return ``Config didn't change`` error.

I didn't forget about

- [x] Tests
- [x] Changelog
- [ ] Documentation

Close #1046

2021-03-16 21:16 UTC, rosik requested changes
The error isn't necessary. The skipping should be preserver, just the location of decision making should be changed.

2021-03-17 09:44 UTC, rosik commented on cartridge/twophase.lua
> +
It shouldn't be skipped in case of the OperationError.

2021-03-18 15:49 UTC, rosik approved these changes

2021-03-18 15:56 UTC, olegrok approved these changes

2021-03-18 16:12 UTC, merged