Add vshard issues
tarantool/cartridge pull request #1528
Opened 2021-08-16 16:30 UTC by yngvar-antonsson

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #941

2021-08-30 22:04 UTC, rosik requested changes

2021-08-30 22:04 UTC, rosik commented on cartridge/issues.lua
> +                if type == 'UNKNOWN_BUCKETS'
With this predicate, a cluster shows issues even before the vshard is bootstrapped, and it's no good, I think. Also, WebUI tests fail because of it.

2021-09-24 14:12 UTC, rosik commented
We've discussed this patch with @no1seman and found it to be harmful.

1. During ansible deployments, it's usual to check for the absence of issues. 
1. There're projects with 200K buckets. 

If we merge this patch, every ansible step will take up to 200 seconds which is unacceptable.

An alternative solution could be introducing a new issues level, but then it wouldn't be an issue at all.

As for the "Invalid configuration" issue, I think it doesn't have much value either. Buckets count difference seems to be nearly impossible to me.

I suggest that we admit this experiment has failed. There's nothing to monitor in the current version of vshard. And if something emerges there someday, this patch could be resurrected.

2021-09-24 14:12 UTC, closed without merging

2021-09-24 14:25 UTC, no1seman commented
OK, let it be closed but there is solution to make special severirty for such issues and this will solve the problem. May be in some unknown future....