Repro test
tarantool/cartridge pull request #1550
Opened 2021-09-02 14:25 UTC by yngvar-antonsson

What has been done? Why? What problem is being solved?

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #1546

2021-09-02 22:25 UTC, rosik reviewed
In general, it looks appropriate, but there's a lot of NITs, find them below.

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +    t.assert_equals(content, {{1}, {2}, {3}})
It may be flaky. The replication is async. Wrap it with `helpers.retrying`

2021-09-02 22:25 UTC, rosik commented on cartridge/confapplier.lua
> +            local old_passwd = user[5]['chap-sha1']
What's 5?

2021-09-02 22:25 UTC, rosik commented on cartridge/confapplier.lua
> +        end
It looks too complicated. I'm sure it could be more concise

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +                },
It could be briefer.

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +    ]])
I suggest checking something like 
```
t.assert_covers(
    box.info.replication,
    {status = 'running'}
)
```

2021-09-02 22:25 UTC, rosik commented on cartridge/confapplier.lua
> +            local old_passwd = user[5]['chap-sha1']
Even if there's no built-in constant, add a comment (preferably with a link to the code or spec)

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +local helpers = require('test.helper')
Please, use modern style:

```lua
local t = require('luatest')
local h = require('test.helper')
local g = t.group()
```

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +        cookie = require('digest').urandom(6):hex(),
`cookie = h.random_cookie(),`

2021-09-02 22:25 UTC, rosik commented on test/integration/master_restart_test.lua
> +                uuid = helpers.uuid('a'),
It may be omitted nowadays

2021-09-02 22:26 UTC, rosik commented on test/integration/master_restart_test.lua
> +local helpers = require('test.helper')
See, for example, https://github.com/tarantool/cartridge/blob/master/test/integration/restart_replication_test.lua

2021-09-02 22:28 UTC, rosik commented on test/integration/master_restart_test.lua
> +    t.assert_equals(content, {{1}, {2}, {3}}, info_replication[2].upstream.message)
It's potentially flaky too.

2021-09-06 12:40 UTC, rosik requested changes

2021-09-06 12:40 UTC, rosik commented on cartridge/confapplier.lua
> +        then
```suggestion
        -- https://github.com/tarantool/tarantool/blob/2.7.3/src/box/lua/schema.lua#L2719-L2724
        -- Don't commit anything if it's already ok.
        if user == nil or user.auth['chap-sha1'] ~= box.schema.user.password(password) then
```

2021-09-06 12:40 UTC, rosik commented on test/integration/master_restart_test.lua
> +        ]])
I suggest adding one more `assert_covers` instead of putting it into the error message

2021-09-07 15:20 UTC, yngvar-antonsson commented
lgtm

2021-09-07 15:21 UTC, rosik approved these changes

2021-09-07 15:23 UTC, merged