Improve the error message in login dialog
tarantool/cartridge pull request #1607
Opened 2021-11-12 11:38 UTC by usenko-timur

* Improve the error message in login dialog.

I didn't forget about

- [x] Tests
- [x] Changelog
- [x] Documentation

Close #600

2021-11-16 09:08 UTC, OlgaYakovleva approved these changes
Verifeid with steps:

1. Cartridge start
2. Log in with a user
3. Set up "Enable auth"
4. Log out as the user from the step2
5. Cartridge stop
6. Try to log in

Get correct error message: "Cannot connect to server. Please try again later."

2021-11-18 11:37 UTC, yngvar-antonsson requested changes

2021-11-18 11:37 UTC, yngvar-antonsson commented on webui/src/store/request/auth.requests.js
> +
redundant empty line

2021-11-18 12:53 UTC, usenko-timur commented on webui/src/store/request/auth.requests.js
> +
Fixed

2021-11-18 13:04 UTC, yngvar-antonsson approved these changes

2021-11-18 13:05 UTC, merged