Restrict RPC calls to work while clisterwide config
tarantool/cartridge pull request #1717
Opened 2022-01-22 00:21 UTC by yngvar-antonsson

I didn't forget about

- [ ] Tests
- [ ] Changelog

Close #1575

2022-01-22 06:49 UTC, olegrok requested changes

2022-01-22 06:49 UTC, olegrok commented on cartridge/rpc.lua
> +        return nil, RemoteCallError:new('Twophase commit is in progress, try again later')
All TDG tests fail after this patch. Please don't do that.

2022-01-23 19:17 UTC, olegrok commented on cartridge/rpc.lua
> +        return nil, RemoteCallError:new('Twophase commit is in progress, try again later')
I pushed my "optimistic" approach https://github.com/tarantool/cartridge/pull/1724

I have not tested it against TDG but seems it doesn't ban anything just add some timeout to wait when config commit will be finished.

2022-01-25 00:14 UTC, yngvar-antonsson commented
Closed in favor of #1724

2022-01-25 00:14 UTC, closed without merging