Add new 2.10 box.cfg options
tarantool/cartridge pull request #1764
Opened 2022-02-22 13:00 UTC by panticonur

Add new 2.10 box.cfg options

- feedback_crashinfo
- iproto_threads
- memtx_allocator
- replication_threads
- slab_alloc_granularity
- sql_cache_size
- txn_timeout
- wal_cleanup_delay
- wal_queue_max_size

I didn't forget about

- [ ] Tests
- [ ] Changelog

Close #1759

2022-02-22 13:18 UTC, yngvar-antonsson requested changes

2022-02-22 13:18 UTC, yngvar-antonsson commented on cartridge/argparse.lua
> +local box_opts = {
please setup your editor to eliminate trailing whitespaces

2022-02-22 13:18 UTC, yngvar-antonsson commented on cartridge/argparse.lua
>      work_dir                 = 'string', -- **string** (**deprecated**)
Please check if some opts are deprecated too

2022-02-28 11:37 UTC, filonenko-mikhail approved these changes

2022-02-28 11:37 UTC, yngvar-antonsson approved these changes

2022-02-28 11:38 UTC, merged