Export vshard config API
tarantool/cartridge pull request #1770
Opened 2022-02-28 13:13 UTC by panticonur

Create public API to get vshard config.

I didn't forget about

- [ ] Tests
- [ ] Changelog

Close #1761

2022-03-01 09:23 UTC, yngvar-antonsson requested changes

2022-03-01 09:23 UTC, yngvar-antonsson commented on cartridge/lua-api/vshard.lua
> +local e_vshard = errors.new_class('vshard api error')
https://github.com/tarantool/errors#naming-conventions

2022-03-01 09:23 UTC, yngvar-antonsson commented on test/integration/vshard_api_test.lua
> +                servers = {
please compact test:

```lua
{
                 roles = {'myrole'},
                 servers = 2
}
```

2022-03-01 09:23 UTC, yngvar-antonsson commented on test/integration/vshard_api_test.lua
> +        cookie = require('digest').urandom(6):hex(),
helpers.random_cookie()

2022-03-01 09:23 UTC, yngvar-antonsson commented on test/integration/vshard_api_test.lua
> +function g.test_get_cfg()
please add a multisharding test. (see example in tests with name multisharding*)

2022-03-01 13:01 UTC, yngvar-antonsson approved these changes

2022-03-01 13:02 UTC, merged

2022-03-09 15:48 UTC, filonenko-mikhail commented on cartridge/lua-api/vshard.lua
> +        vshard_groups = {default = conf.vshard}
No

2022-03-09 15:54 UTC, olegrok commented on cartridge/lua-api/vshard.lua
> +        vshard_groups = {default = conf.vshard}
But there is `conf = confapplier.*get_readonly()*` above

2022-03-10 14:12 UTC, filonenko-mikhail commented on cartridge/lua-api/vshard.lua
> +        vshard_groups = {default = conf.vshard}
Conf is not used below as destination. But you are right — code is not clean.