Allow to bootstrap cartridge cluster from existing cluster
tarantool/cartridge pull request #1893
Opened 2022-08-26 13:04 UTC by yngvar-antonsson

I didn't forget about

- [ ] Tests
- [ ] Changelog
- [ ] Documentation

Close #1842

2022-08-29 07:04 UTC, filonenko-mikhail commented on CHANGELOG.rst
> +- Allow to bootstrap cartridge from existing cluster via argparse option
Source is cluster, and is target also cluster or just single node?
Could you please describe a little particulary.

2022-08-29 07:06 UTC, filonenko-mikhail commented on rst/cartridge_admin.rst
> +Valid topology should contain **same** replicasets uuids for each replicaset
Lets start to descrbe valid configuration. Eg
Valid configuration is:
  - valid topology.yaml (or edit topology)

2022-08-29 07:07 UTC, filonenko-mikhail commented on rst/cartridge_admin.rst
> +Valid topology should contain **same** replicasets uuids for each replicaset
The data will be transfered using iproto replication.

2022-08-29 07:11 UTC, filonenko-mikhail approved these changes

2022-08-30 05:47 UTC, grafin requested changes
Thanks for the PR! Just one minor comment from me.

2022-08-30 05:47 UTC, grafin commented on rst/cartridge_admin.rst
> +  read-only before bootstraping target cluster.
I'm not sure, that this will work. Original cluster must write new members to `_cluster` space, and it will fail to do so, if it is read-only.

2022-08-30 11:38 UTC, p7nov requested changes
The doc addition is good.
I've got some minor edits (mostly articles, see my suggestions) and a couple of improvement ideas.

2022-08-30 11:38 UTC, p7nov commented on rst/cartridge_admin.rst
> +``TARANTOOL_BOOTSTRAP_FROM=admin:SECRET-ORIGINAL-CLUSTER-COOKIE@HOST:MASTER_PORT``.
```suggestion
(Optional) You can bootstrap a cluster from an existing cluster (*original* cluster in the example
 below) via the argparse option ``TARANTOOL_BOOTSTRAP_FROM`` or ``--bootstrap_from``
 in the following form: 
 ``TARANTOOL_BOOTSTRAP_FROM=admin:SECRET-ORIGINAL-CLUSTER-COOKIE@HOST:MASTER_PORT``.
```

2022-08-30 11:38 UTC, p7nov commented on rst/cartridge_admin.rst
> +and instances uuids that **differ** from original cluster.
```suggestion
Make sure that you've prepared a valid configuration for the target cluster.
A valid topology should contain the **same** *replicaset uuids* for each replicaset
and *instance uuids* that **differ** from original cluster.
```

2022-08-30 11:38 UTC, p7nov commented on rst/cartridge_admin.rst
> +  (for example, data nodes only) instead of full cluster.
```suggestion
- You can bootstrap specific replicasets from a cluster
  (for example, data nodes only) instead of the whole cluster.
```

2022-08-30 11:38 UTC, p7nov commented on rst/cartridge_admin.rst
> +(Optional) You can bootstrap cluster from existing cluster (*original* cluster in example)
For better structure, I would add this part under a separate heading. Something like *Bootstrapping from an existing cluster*.

2022-08-30 11:38 UTC, p7nov commented on rst/cartridge_admin.rst
> +  in original cluster before bootstraping target cluster.
"Make sure you aren't trying to load data" sounds a bit weird: you either try to do something or not.
So, we can say directly something like "Don't load data in the target cluster while bootstrapping" or "... unless bootstrapping is completed". Will this be correct?

2022-08-31 01:17 UTC, p7nov approved these changes
Nice, just three more minor edits.

2022-08-31 01:17 UTC, p7nov commented on rst/cartridge_admin.rst
> +Setup cluster
For consistency, this should be either **Setting up cluster** (most of other headings are in the gerund form "Doing something") or **Cluster setup** (simple noun form).

2022-08-31 04:10 UTC, p7nov commented on rst/cartridge_admin.rst
> + ``TARANTOOL_BOOTSTRAP_FROM=admin:SECRET-ORIGINAL-CLUSTER-COOKIE@HOST:MASTER_PORT``.
```suggestion
You can bootstrap a cluster from an existing cluster (*original* cluster in the example
below) via the argparse option ``TARANTOOL_BOOTSTRAP_FROM`` or ``--bootstrap_from``
in the following form: 
``TARANTOOL_BOOTSTRAP_FROM=admin:SECRET-ORIGINAL-CLUSTER-COOKIE@HOST:MASTER_PORT``.
```

2022-08-31 07:58 UTC, merged